/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.Vehiculos;
import Logica.Vehiculos;
import Datos.ObjVehiculo;
import javax.swing.JOptionPane;
/**
 *
 * @author triamus
 */
public class FrmIngresarVehiculos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmIngresarVehiculos.class.getName());

    /**
     * Creates new form FrmIngresarVehiculos
     */
    public FrmIngresarVehiculos() {
        initComponents();
        
        cargarMarcas();
    }
    
    private void cargarMarcas() {
    cmbMarca.removeAllItems();
    cmbMarca.addItem("Seleccione una marca...");
    cmbMarca.addItem("Toyota");
    cmbMarca.addItem("Hyundai");
    cmbMarca.addItem("Nissan");
    cmbMarca.addItem("Kia");
    cmbMarca.addItem("Honda");
    cmbMarca.addItem("Mitsubishi");
    cmbMarca.addItem("Suzuki");
    cmbMarca.addItem("Mazda");
    cmbMarca.addItem("Ford");
    cmbMarca.addItem("Chevrolet");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbMarca = new javax.swing.JComboBox<>();
        cmbModelo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtKm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbMotor = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbCombustible = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registro de Vehiculos");

        jLabel3.setText("Placa:");

        jLabel4.setText("Marca:");

        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Marca", "Toyota", "Hyundai", "Nissan", "Kia", "Honda", "Mitsubishi", "Suzuki", "Mazda", "Ford", "Chevrolet", "Otro" }));
        cmbMarca.addItemListener(this::cmbMarcaItemStateChanged);
        cmbMarca.addActionListener(this::cmbMarcaActionPerformed);

        cmbModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        jLabel5.setText("Modelo:");

        jLabel6.setText("Anio:");

        txtAnio.addActionListener(this::txtAnioActionPerformed);

        jLabel7.setText("Kilometraje:");

        txtKm.addActionListener(this::txtKmActionPerformed);

        jLabel10.setText("Motor:");

        cmbMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Electrico", "Combustion interna", "Hibrido" }));
        cmbMotor.addItemListener(this::cmbMotorItemStateChanged);

        jLabel11.setText("Combustible:");

        cmbCombustible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));

        jLabel12.setText("--------------------------------------------------------------------------------------------------------------------------------------------");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPlaca)
                                            .addComponent(cmbModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbMarca, 0, 147, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(jLabel9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                    .addComponent(txtKm)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGuardar)
                                        .addGap(96, 96, 96)))))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cmbCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(82, 82, 82))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cmbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarcaActionPerformed
        // TODO add your handling code here:
   
        
    }//GEN-LAST:event_cmbMarcaActionPerformed

    private void cmbMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMarcaItemStateChanged
        // TODO add your handling code here:
        
        // 1. Validamos que el evento ocurra cuando el usuario selecciona un elemento
    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        
        // 2. Limpiamos el combo de modelos para que no se mezclen los modelos anteriores
        cmbModelo.removeAllItems();
        
        // 3. Obtenemos el número de la opción seleccionada en el combo de marcas
        int opcionMarca = cmbMarca.getSelectedIndex();
        
        // 4. Usamos el switch para evaluar qué marca eligió el usuario
        switch (opcionMarca) {
            case 1: // Toyota
                cmbModelo.addItem("Hilux");
                cmbModelo.addItem("Corolla Cross");
                cmbModelo.addItem("Yaris");
                cmbModelo.addItem("Prado");
                cmbModelo.addItem("Raize");
                break;
                
            case 2: // Hyundai
                cmbModelo.addItem("Tucson");
                cmbModelo.addItem("Elantra");
                cmbModelo.addItem("Santa Fe");
                cmbModelo.addItem("Creta");
                cmbModelo.addItem("Accent");
                break;
                
            case 3: // Nissan
                cmbModelo.addItem("Frontier");
                cmbModelo.addItem("Sentra");
                cmbModelo.addItem("Kicks");
                cmbModelo.addItem("X-Trail");
                cmbModelo.addItem("Versa");
                break;
                
            case 4: // Kia
                cmbModelo.addItem("Sportage");
                cmbModelo.addItem("Rio");
                cmbModelo.addItem("Seltos");
                cmbModelo.addItem("Sorento");
                cmbModelo.addItem("Picanto");
                break;
                
            case 5: // Honda
                cmbModelo.addItem("CR-V");
                cmbModelo.addItem("Civic");
                cmbModelo.addItem("HR-V");
                cmbModelo.addItem("Pilot");
                cmbModelo.addItem("Fit");
                break;
                
            case 6: // Mitsubishi
                cmbModelo.addItem("Montero");
                cmbModelo.addItem("L200");
                cmbModelo.addItem("ASX");
                cmbModelo.addItem("Outlander");
                cmbModelo.addItem("Mirage");
                break;
                
            case 7: // Suzuki
                cmbModelo.addItem("Vitara");
                cmbModelo.addItem("Swift");
                cmbModelo.addItem("Jimny");
                cmbModelo.addItem("S-Cross");
                cmbModelo.addItem("Ertiga");
                break;
                
            case 8: // Mazda
                cmbModelo.addItem("CX-5");
                cmbModelo.addItem("Mazda 3");
                cmbModelo.addItem("CX-30");
                cmbModelo.addItem("BT-50");
                cmbModelo.addItem("Mazda 2");
                break;
                
            case 9: // Ford
                cmbModelo.addItem("Ranger");
                cmbModelo.addItem("Escape");
                cmbModelo.addItem("Explorer");
                cmbModelo.addItem("Edge");
                cmbModelo.addItem("F-150");
                break;
                
            case 10: // Chevrolet
                cmbModelo.addItem("Tracker");
                cmbModelo.addItem("Colorado");
                cmbModelo.addItem("Tahoe");
                cmbModelo.addItem("Captiva");
                cmbModelo.addItem("Onix");
                break;
                
            default: 
                cmbModelo.addItem("Seleccione");
                
                break;
        }
    }
    }//GEN-LAST:event_cmbMarcaItemStateChanged

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void txtKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmActionPerformed

    private void cmbMotorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMotorItemStateChanged
        // TODO add your handling code here:
        
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            
            //limpiamos lista
            cmbCombustible.removeAllItems();
            
            int opcion = cmbMotor.getSelectedIndex();
            
            switch(opcion){
                case 1: cmbCombustible.addItem("KWH");
                    break;
                case 2: 
                    cmbCombustible.addItem("Gasolina");
                    cmbCombustible.addItem("Diesel");
                    break;
                case 3: cmbCombustible.addItem("Gasolina + KWH");
                cmbCombustible.addItem("Diesel + KWH");
                    break;
                    
                default: cmbCombustible.addItem("Seleccione...");
                    break;
                
            }
        }
    }//GEN-LAST:event_cmbMotorItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        String placa = txtPlaca.getText().trim();
        String TextoKm = txtKm.getText().trim();
        String TextoAnio = txtAnio.getText().trim();
        int anio =0;
        float km = 0;
        
        //validaciones antes de guadar
        //camnpos que no esten vacios
        
        if(Vehiculos.placaRepetida(placa)==1){
            JOptionPane.showMessageDialog(this, "Esta placa ya existe en el registro","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if((placa.isEmpty()) || (TextoKm.isEmpty()) || (TextoAnio.isEmpty())){
            
            JOptionPane.showMessageDialog(this, "[!] Por favor completa los campos","Error",JOptionPane.ERROR_MESSAGE);

            if(TextoAnio.isEmpty()){
                txtAnio.requestFocus();
            }
            
            if(TextoKm.isEmpty()){
                txtKm.requestFocus();
            }
            
            if(placa.isEmpty()){
                txtPlaca.requestFocus();
            }
            return;
        }
        
        int indiceMarca = cmbMarca.getSelectedIndex();
        int indiceMotor = cmbMotor.getSelectedIndex();
        
        if((indiceMarca ==0)){
            JOptionPane.showMessageDialog(this, "Seleccione una marca","Error",JOptionPane.WARNING_MESSAGE);
            
            cmbMarca.requestFocus();
            return;
        }
        
        if((indiceMotor ==0)){
            JOptionPane.showMessageDialog(this, "Seleccione el tipo de motor","Error",JOptionPane.WARNING_MESSAGE);
            
            cmbMotor.requestFocus();
            return;
        }
        
        
        try {
            //convertirlo
            anio =Integer.parseInt(TextoAnio);
            
            
            //si escribio alfo dififernte
        } catch (NumberFormatException e) {
            
            javax.swing.JOptionPane.showMessageDialog(this, "[!] El anio del vehiculo solo debe de contener numero",
                    "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            
            //ux en psocionar donde debe d ecorregir
            txtAnio.requestFocus();
            return;
        }
        
        //  Validar que sea un año razonable
        if (anio < 1900 || anio > 2026) {
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "[!] Por favor, digite un año válido (ej. 2020, 2024).", 
                "Atención", 
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            txtAnio.requestFocus();
            return;
        }
        
        try {
            km = Integer.parseInt(TextoKm);
        } catch (NumberFormatException e) {
            
            javax.swing.JOptionPane.showMessageDialog(this, "[!] El km del vehiculo solo debe de contener numero",
                    "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            
            //ux en psocionar donde debe d ecorregir
            txtKm.requestFocus();
            return;
        }
        
        
        //guardado
        
        String marca = Vehiculos.marcas[indiceMarca-1];
        //parseamos a sstring la opcion que selecciono
        String Modelo = cmbModelo.getSelectedItem().toString();
        
        String motor = cmbMotor.getSelectedItem().toString();
        
        String combustible = cmbCombustible.getSelectedItem().toString();
        String estado = "Activo";
        
        
        
        
        ObjVehiculo nuevoVehiculo = new ObjVehiculo();
        Vehiculos miLogica = new Vehiculos();
        
        nuevoVehiculo.setPlaca(placa);//
        nuevoVehiculo.setMarca(marca);//
        nuevoVehiculo.setModelo(Modelo);//
        nuevoVehiculo.setTipoVehiculo(motor);//
        nuevoVehiculo.setCombustible(combustible);//
        nuevoVehiculo.setKilometroActual(km);//
        nuevoVehiculo.setAnio(anio);//
        nuevoVehiculo.setEstado(estado);
        
        miLogica.guardarVehiculo(nuevoVehiculo);
        
        JOptionPane.showMessageDialog(this, "¡Vehiculo registrado con éxito!", "Información", JOptionPane.INFORMATION_MESSAGE);

        txtAnio.setText("");
        txtKm.setText("");
        txtPlaca.setText("");
        cmbMarca.setSelectedIndex(0);
        cmbModelo.setSelectedIndex(0);
        cmbMotor.setSelectedIndex(0);
        cmbCombustible.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmIngresarVehiculos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbCombustible;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JComboBox<String> cmbModelo;
    private javax.swing.JComboBox<String> cmbMotor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtKm;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
