/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.Reportes;
import Presentacion.Usuario.FrmGestionUsuarios;
import Presentacion.Gmante.FrmGestionMante;
import Presentacion.vehiculos.FrmGestionVehiculos;
import Presentacion.AsignacionMante.FrmAsignarMantenimiento;
import Presentacion.BoletaCombus.FrmBoletaCombus;
import Presentacion.BoletaTaller.FrmBoletaTaller;
import Presentacion.GestionMecanicos.FrmGestionMecanicos;
import Presentacion.Loggin;
import Presentacion.MenusPrincipales.FrmMenuAdmin;
import Presentacion.MenusPrincipales.FrmMenuOperador;
/**
 *
 * @author triamus
 */
public class FrmMenuVenci extends javax.swing.JFrame {
    
    
    private boolean rolActual;
    /**
     * Creates new form FrmMenuAdmin
     */
    public FrmMenuVenci(boolean rol) {
        initComponents();
        this.rolActual = rol;
        setLocationRelativeTo(null); // Centra la ventana en pantalla
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelContenedorCentrado = new javax.swing.JPanel();
        jPanelTarjetaMenu = new javax.swing.JPanel();
        lblSubtitulo = new javax.swing.JLabel();
        jPanelGridBotones = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DELTAMOTORS - ADMINISTRADOR");

        jPanelPrincipal.setBackground(new java.awt.Color(240, 243, 246));
        jPanelPrincipal.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(41, 128, 185));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("DELTAMOTORS - MANTENIMIENTOS VENCIDOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 10, 20);
        jPanelPrincipal.add(lblTitulo, gridBagConstraints);

        jSeparator1.setForeground(new java.awt.Color(200, 200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 20, 40);
        jPanelPrincipal.add(jSeparator1, gridBagConstraints);

        jPanelContenedorCentrado.setOpaque(false);
        jPanelContenedorCentrado.setLayout(new java.awt.GridBagLayout());

        jPanelTarjetaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTarjetaMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 40, 35, 40));
        jPanelTarjetaMenu.setLayout(new java.awt.GridBagLayout());

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(127, 140, 141));
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("Panel de Control y Gestión del Sistema");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        jPanelTarjetaMenu.add(lblSubtitulo, gridBagConstraints);

        jPanelGridBotones.setOpaque(false);
        jPanelGridBotones.setLayout(new java.awt.GridLayout(5, 2, 20, 15));

        jButton8.setBackground(new java.awt.Color(52, 73, 94));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Reportes del Periodo con Fechas");
        jButton8.setFocusPainted(false);
        jButton8.setPreferredSize(new java.awt.Dimension(230, 42));
        jPanelGridBotones.add(jButton8);

        jButton9.setBackground(new java.awt.Color(52, 73, 94));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Reportes del Periodo Kilometraje");
        jButton9.setFocusPainted(false);
        jButton9.setPreferredSize(new java.awt.Dimension(230, 42));
        jPanelGridBotones.add(jButton9);

        btnRegresar.setBackground(new java.awt.Color(231, 76, 60));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setFocusPainted(false);
        btnRegresar.setPreferredSize(new java.awt.Dimension(230, 42));
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);
        jPanelGridBotones.add(btnRegresar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelTarjetaMenu.add(jPanelGridBotones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanelContenedorCentrado.add(jPanelTarjetaMenu, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 30, 20);
        jPanelPrincipal.add(jPanelContenedorCentrado, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        if (rolActual) {
            FrmMenuAdmin panelAdmin = new FrmMenuAdmin(this.rolActual,null);
            panelAdmin.setVisible(true);
        }else{
            FrmMenuOperador panelOpera = new FrmMenuOperador(this.rolActual);
            panelOpera.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            
        }

        java.awt.EventQueue.invokeLater(() -> new FrmMenuVenci(false).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanelContenedorCentrado;
    private javax.swing.JPanel jPanelGridBotones;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelTarjetaMenu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}