/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.Usuarios;

import Presentacion.Usuarios.FrmConsultarUsuarios;

/**
 *
 * @author triamus
 */
public class FrmMenuUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuUsuarios.class.getName());

    /**
     * Creates new form FrmMenuUsuarios
     */
    public FrmMenuUsuarios() {
        initComponents();
        
      // Centrar la ventana en la pantalla
        setLocationRelativeTo(null);
        
        // Desactiva la capacidad de maximizar la ventana
setResizable(false);
        // Fondo oscuro unificado idéntico al de tus otros formularios
        getContentPane().setBackground(new java.awt.Color(24, 26, 33));
        
        // Estilo del Título
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        // Estilo de botones
        java.awt.Color colorAzul = new java.awt.Color(41, 128, 185);
        java.awt.Color colorGris = new java.awt.Color(50, 55, 65);
        
        estilizarBoton(btnIrRegistrar, colorAzul);
        estilizarBoton(btnIrConsultar, colorAzul);
        estilizarBoton(btnRegresar, colorGris);
    }
    
    private void estilizarBoton(javax.swing.JButton boton, java.awt.Color colorFondo) {
        boton.setBackground(colorFondo);
        boton.setForeground(java.awt.Color.white);
        boton.setFocusPainted(false);
        boton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnIrRegistrar = new javax.swing.JButton();
        btnIrConsultar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);

        jLabel1.setText("GESTION DE USUARIOS");

        btnIrRegistrar.setText("Ingresar Usuarios");
        btnIrRegistrar.addActionListener(this::btnIrRegistrarActionPerformed);

        btnIrConsultar.setText("Eliminar/Modificar");
        btnIrConsultar.addActionListener(this::btnIrConsultarActionPerformed);

        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIrConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIrRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnIrRegistrar)
                .addGap(18, 18, 18)
                .addComponent(btnIrConsultar)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrConsultarActionPerformed
        // TODO add your handling code here:
        
        FrmConsultarUsuarios ventanaConsultas = new FrmConsultarUsuarios();
        ventanaConsultas.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnIrConsultarActionPerformed

    private void btnIrRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrRegistrarActionPerformed
        // TODO add your handling code here:
        
        FrmRegistrarUsuario ventanaRegistro = new FrmRegistrarUsuario();
        ventanaRegistro.setVisible(true);
        
        //cerar vernatna actual
        this.dispose();
    }//GEN-LAST:event_btnIrRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIrConsultar;
    private javax.swing.JButton btnIrRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
