/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.Usuario;
import Datos.Estructuras;
import Datos.objUsuarios;
import Logica.logicaUsuarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author triamus
 */
public class FrmGestionUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestionUsuarios.class.getName());

    /**
     * Creates new form FrmGestionUsuarios
     */
    public FrmGestionUsuarios() {
        initComponents();
        metodosCarga();
        
    txtBuscador.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
    @Override
    public void insertUpdate(javax.swing.event.DocumentEvent e) {
        filtrarUsuarios();
    }

    @Override
    public void removeUpdate(javax.swing.event.DocumentEvent e) {
        filtrarUsuarios();
    }

    @Override
    public void changedUpdate(javax.swing.event.DocumentEvent e) {
        filtrarUsuarios();
    }
    });
                }
    
    private void filtrarUsuarios(){
        String filtro = txtBuscador.getText().trim().toLowerCase();
        
        //Leer los datos actuales
        Estructuras est = new Estructuras();
        est.leerArchivoUsuarios();
        
        ArrayList<Datos.objUsuarios> lista = est.getListaUsuarios();
        
        //lista temporal para almacenar los que aparezcan
        ArrayList<Datos.objUsuarios> listaFiltrada = new ArrayList<>();
        
        for (int i = 0; i < lista.size(); i++) {
            objUsuarios u = lista.get(i);
            
            //lo que podria buscar
            String id = String.valueOf(u.getId());
            String nombre = u.getNombre().toLowerCase();
            String cedula = u.getCedula().toLowerCase();
            String rol = u.getRol().toLowerCase();
            
            if (id.contains(filtro)|| nombre.contains(filtro) || cedula.contains(filtro)|| rol.contains(filtro)){
                listaFiltrada.add(u);
            }
        }
        
        // 3. Rellenamos la tabla con los datos filtrados
    String[] columnas = {"ID", "Usuario","Cedula","Rol", "Estado"};
    Object[][] datos = new Object[listaFiltrada.size()][5];
    
    for (int i = 0; i < listaFiltrada.size(); i++) {
        Datos.objUsuarios u = listaFiltrada.get(i);
        datos[i][0] = u.getId();
        datos[i][1] = u.getNombre();
        datos[i][2] = u.getCedula();
        datos[i][3] = u.getRol();
        datos[i][4] = u.getEstado();
    }
    
    DefaultTableModel modelo = new DefaultTableModel(datos,columnas);
    tblUser.setModel(modelo);
    }
    private void metodosCarga(){
        cargarTabla();
        configurarPlaceholder(txtUsuario, "Ingrese Usuario");
        configurarPlaceholder(txtCedula, "Cedula");
        configurarPlaceholder(txtContrasena, "Ingrese una contrasena");
        

    }

    private void cargarTabla(){
        
        Estructuras est = new Estructuras();
        est.leerArchivoUsuarios();
        
        //tener la lista cargada
        ArrayList<Datos.objUsuarios> lista = est.getListaUsuarios();
        
        String[] columnas = {"Id","Usuario","Cedula","Rol","Estado"};
        
        //matriz para almacenar los datos
        Object[][] datos = new Object[lista.size()][5];
        
        //rellenar matriz
        for (int i = 0; i < lista.size(); i++) {
            Datos.objUsuarios u = lista.get(i);
            
            datos[i][0] = u.getId();
            datos[i][1] = u.getNombre();
            datos[i][2] = u.getCedula();
            datos[i][3] = u.getRol();
            datos[i][4] = u.getEstado();
        }
        
        //asiganr los valores a las tablas
        DefaultTableModel modelo = new DefaultTableModel(datos, columnas);
        tblUser.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        btnGuardarUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 50));

        txtUsuario.setPreferredSize(new java.awt.Dimension(150, 28));

        jLabel3.setText("Cedula:");

        jLabel4.setText("Contrasena:");

        txtContrasena.setText("jPasswordField1");

        jLabel5.setText("Rol:");

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Operador", "Administrador" }));

        btnGuardarUser.setText("Guardar");
        btnGuardarUser.addActionListener(this::btnGuardarUserActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGuardarUser)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel3))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtContrasena)
                                    .addComponent(txtCedula)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnGuardarUser)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresar Usuario", jPanel2);

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUser);

        jLabel6.setText("Buscar: ");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Eliminar/Modificar", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUserActionPerformed
        // TODO add your handling code here:
        
        String nombreUsuario = txtUsuario.getText().trim();
        String cedula = txtCedula.getText().trim();
        String password = new String(txtContrasena.getPassword()).trim();
        String rol = cmbRol.getSelectedItem().toString();
        String estado = "Activo";
        
        // Verificamos el índice 0 del combo desde la vista antes de enviar
        if (cmbRol.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "¡Error! Por favor, seleccione un rol válido.");
        cmbRol.requestFocus();
        return;
        }
        
        
        //instanciamos
        logicaUsuarios usuario = new logicaUsuarios();
        
        boolean existenciaUser = usuario.existenciaUser(nombreUsuario, cedula);
        if(existenciaUser){
            JOptionPane.showMessageDialog(this, "¡Usuario o cedula existente en los registros!", "Información", JOptionPane.ERROR_MESSAGE);
            
            return;
        }
        if(nombreUsuario.isEmpty()){
            JOptionPane.showMessageDialog(this, "¡Por favor llene el campo de usuario!", "Información", JOptionPane.ERROR_MESSAGE);
            txtUsuario.requestFocus();
            return;
        }
        
        if(cedula.isEmpty()){
            JOptionPane.showMessageDialog(this, "¡Por favor llene el campo de cedula!", "Información", JOptionPane.ERROR_MESSAGE);
            txtCedula.requestFocus();
            return;
        }
        
        if(password.isEmpty()){
            JOptionPane.showMessageDialog(this, "¡Por favor llene el campo de contrasena!", "Información", JOptionPane.ERROR_MESSAGE);
            txtContrasena.requestFocus();
            return;
        }
        boolean exito = usuario.registrarUsuario(nombreUsuario,cedula,password,rol,estado);
        
        if(exito){
            JOptionPane.showMessageDialog(this, "¡Usuario registrado con éxito!", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            txtUsuario.setText("");
            txtCedula.setText("");
            txtContrasena.setText("");
            cmbRol.setSelectedIndex(0);
            
            metodosCarga();
            
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo registrar el usuario. Verifique si ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarUserActionPerformed

    private void configurarPlaceholder(javax.swing.JTextField textField, String textoPlaceholder) {
    // Texto inicial y color gris clarito para simular placeholder
    textField.setText(textoPlaceholder);
    textField.setForeground(new java.awt.Color(153, 153, 153));

    textField.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            // Cuando el usuario hace clic y el campo tiene el texto de guía, se limpia
            if (textField.getText().equals(textoPlaceholder)) {
                textField.setText("");
                textField.setForeground(new java.awt.Color(0, 0, 0)); // Color negro normal al escribir
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            // Si el usuario sale del campo y lo dejó vacío, vuelve a aparecer la guía
            if (textField.getText().trim().isEmpty()) {
                textField.setText(textoPlaceholder);
                textField.setForeground(new java.awt.Color(153, 153, 153)); // Color gris guía
            }
        }
    });
}
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        //verificamos qu efila selecciono el usuario
        int filaSeleccionada = tblUser.getSelectedRow();
        
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario de la tabla para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        //extraemos el id para usarlo
        int idUsuario = Integer.parseInt(tblUser.getValueAt(filaSeleccionada, 0).toString());
        String nombreUsuario = tblUser.getValueAt(filaSeleccionada, 1).toString();
        
        int respuesta = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea eliminar al usuario: " + nombreUsuario + "?", 
            "Confirmar eliminación", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
        
        if (respuesta == JOptionPane.YES_OPTION) {
        // 4. Llamamos a un método de la lógica o estructuras para borrarlo
        Datos.Estructuras est = new Datos.Estructuras();
        est.leerArchivoUsuarios();
        // Buscamos y removemos el usuario de la lista en memoria por su ID
        boolean eliminado = false;
        ArrayList<Datos.objUsuarios> lista = est.getListaUsuarios();
        
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).getId() == idUsuario) {
                lista.remove(i);
                eliminado = true;
                break;
            }
        }
        
        if (eliminado) {
            // 5. Sobrescribimos el archivo de texto con la lista actualizada sin ese usuario
            est.escribeArchivoUsuarios();
            
            JOptionPane.showMessageDialog(this, "¡Usuario eliminado con éxito!", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            // 6. Recargamos la tabla para que refleje los cambios al instante
            cargarTabla(); 
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo encontrar el usuario en los registros.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        int filaSeleccionada = tblUser.getSelectedRow();
        
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        //extrare los datos
        // Correcto orden: (filaSeleccionada, numeroDeColumna)
       int id = Integer.parseInt(tblUser.getValueAt(filaSeleccionada, 0).toString());
        String nombre = tblUser.getValueAt(filaSeleccionada, 1).toString();

        String rol = tblUser.getValueAt(filaSeleccionada, 3).toString();
        String estado = tblUser.getValueAt(filaSeleccionada, 4).toString();

        // Instancias exactamente con los 4 datos que recibe el constructor de la ventana flotante:
        DlgModificarVehiculo ventanaFlotante = new DlgModificarVehiculo(this, true, id, nombre,  rol,estado);
        ventanaFlotante.setVisible(true);

    
    // 5. Cuando el usuario cierre la ventanita flotante, recargamos la tabla automáticamente
    cargarTabla();
    }//GEN-LAST:event_btnModificarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestionUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarUser;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
