/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.MenusPrincipales;
import Presentacion.Usuario.FrmGestionUsuarios;
import Presentacion.Gmante.FrmGestionMante;
import Presentacion.vehiculos.FrmGestionVehiculos;
import Presentacion.AsignacionMante.FrmAsignarMantenimiento;
import Presentacion.BoletaCombus.FrmBoletaCombus;
import Presentacion.BoletaTaller.FrmBoletaTaller;
import Presentacion.GestionMecanicos.FrmGestionMecanicos;
import Presentacion.Loggin;
import Presentacion.Reportes.FrmMenuVenci;
import Presentacion.Usuario.FrmBoletaCambiarContra;
/**
 *
 * @author triamus
 */
public class FrmMenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName());
    private boolean rolAdmin;
    private String nameUser;
    /**
     * Creates new form FrmMenuAdmin
     */
    public FrmMenuAdmin(boolean rol,String user) {
        initComponents();
        this.rolAdmin = rol;
        this.nameUser = user;
        setLocationRelativeTo(null); // Centra la ventana en pantalla
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelContenedorCentrado = new javax.swing.JPanel();
        jPanelTarjetaMenu = new javax.swing.JPanel();
        lblSubtitulo = new javax.swing.JLabel();
        jPanelGridBotones = new javax.swing.JPanel();
        btnGestionUser = new javax.swing.JButton();
        btnGestionVehiculos = new javax.swing.JButton();
        btnGestionMante = new javax.swing.JButton();
        btnAsigancion = new javax.swing.JButton();
        btnBoletaCombus = new javax.swing.JButton();
        btnGestionMeca = new javax.swing.JButton();
        btnBoletataller = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DELTAMOTORS - ADMINISTRADOR");

        jPanelPrincipal.setBackground(new java.awt.Color(240, 243, 246));
        jPanelPrincipal.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(41, 128, 185));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("DELTAMOTORS - ADMINISTRADOR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 10, 20);
        jPanelPrincipal.add(lblTitulo, gridBagConstraints);

        jSeparator1.setForeground(new java.awt.Color(200, 200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 20, 40);
        jPanelPrincipal.add(jSeparator1, gridBagConstraints);

        jPanelContenedorCentrado.setOpaque(false);
        jPanelContenedorCentrado.setLayout(new java.awt.GridBagLayout());

        jPanelTarjetaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTarjetaMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 40, 35, 40));
        jPanelTarjetaMenu.setLayout(new java.awt.GridBagLayout());

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(127, 140, 141));
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("Panel de Control y Gestión del Sistema");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        jPanelTarjetaMenu.add(lblSubtitulo, gridBagConstraints);

        jPanelGridBotones.setOpaque(false);
        jPanelGridBotones.setLayout(new java.awt.GridLayout(5, 2, 20, 15));

        btnGestionUser.setBackground(new java.awt.Color(41, 128, 185));
        btnGestionUser.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGestionUser.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionUser.setText("Gestión Usuarios");
        btnGestionUser.setFocusPainted(false);
        btnGestionUser.setPreferredSize(new java.awt.Dimension(230, 42));
        btnGestionUser.addActionListener(this::btnGestionUserActionPerformed);
        jPanelGridBotones.add(btnGestionUser);

        btnGestionVehiculos.setBackground(new java.awt.Color(41, 128, 185));
        btnGestionVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGestionVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionVehiculos.setText("Gestión Vehículos");
        btnGestionVehiculos.setFocusPainted(false);
        btnGestionVehiculos.setPreferredSize(new java.awt.Dimension(230, 42));
        btnGestionVehiculos.addActionListener(this::btnGestionVehiculosActionPerformed);
        jPanelGridBotones.add(btnGestionVehiculos);

        btnGestionMante.setBackground(new java.awt.Color(41, 128, 185));
        btnGestionMante.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGestionMante.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionMante.setText("Gestión Mantenimientos");
        btnGestionMante.setFocusPainted(false);
        btnGestionMante.setPreferredSize(new java.awt.Dimension(230, 42));
        btnGestionMante.addActionListener(this::btnGestionManteActionPerformed);
        jPanelGridBotones.add(btnGestionMante);

        btnAsigancion.setBackground(new java.awt.Color(41, 128, 185));
        btnAsigancion.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAsigancion.setForeground(new java.awt.Color(255, 255, 255));
        btnAsigancion.setText("Asignación de Mantenimientos");
        btnAsigancion.setFocusPainted(false);
        btnAsigancion.setPreferredSize(new java.awt.Dimension(230, 42));
        btnAsigancion.addActionListener(this::btnAsigancionActionPerformed);
        jPanelGridBotones.add(btnAsigancion);

        btnBoletaCombus.setBackground(new java.awt.Color(52, 73, 94));
        btnBoletaCombus.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnBoletaCombus.setForeground(new java.awt.Color(255, 255, 255));
        btnBoletaCombus.setText("Boleta de Combustible");
        btnBoletaCombus.setFocusPainted(false);
        btnBoletaCombus.setPreferredSize(new java.awt.Dimension(230, 42));
        btnBoletaCombus.addActionListener(this::btnBoletaCombusActionPerformed);
        jPanelGridBotones.add(btnBoletaCombus);

        btnGestionMeca.setBackground(new java.awt.Color(52, 73, 94));
        btnGestionMeca.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGestionMeca.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionMeca.setText("Gestión de Mecánicos");
        btnGestionMeca.setFocusPainted(false);
        btnGestionMeca.setPreferredSize(new java.awt.Dimension(230, 42));
        btnGestionMeca.addActionListener(this::btnGestionMecaActionPerformed);
        jPanelGridBotones.add(btnGestionMeca);

        btnBoletataller.setBackground(new java.awt.Color(52, 73, 94));
        btnBoletataller.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnBoletataller.setForeground(new java.awt.Color(255, 255, 255));
        btnBoletataller.setText("Boleta de Taller");
        btnBoletataller.setFocusPainted(false);
        btnBoletataller.setPreferredSize(new java.awt.Dimension(230, 42));
        btnBoletataller.addActionListener(this::btnBoletatallerActionPerformed);
        jPanelGridBotones.add(btnBoletataller);

        btnReportes.setBackground(new java.awt.Color(52, 73, 94));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes del Vencimientos");
        btnReportes.setFocusPainted(false);
        btnReportes.setPreferredSize(new java.awt.Dimension(230, 42));
        btnReportes.addActionListener(this::btnReportesActionPerformed);
        jPanelGridBotones.add(btnReportes);

        btnChangePass.setBackground(new java.awt.Color(52, 73, 94));
        btnChangePass.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnChangePass.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePass.setText("Cambiar Contrasena");
        btnChangePass.setFocusPainted(false);
        btnChangePass.setPreferredSize(new java.awt.Dimension(230, 42));
        btnChangePass.addActionListener(this::btnChangePassActionPerformed);
        jPanelGridBotones.add(btnChangePass);

        btnCerrar.setBackground(new java.awt.Color(231, 76, 60));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.setFocusPainted(false);
        btnCerrar.setPreferredSize(new java.awt.Dimension(230, 42));
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);
        jPanelGridBotones.add(btnCerrar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelTarjetaMenu.add(jPanelGridBotones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanelContenedorCentrado.add(jPanelTarjetaMenu, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 30, 20);
        jPanelPrincipal.add(jPanelContenedorCentrado, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUserActionPerformed
        FrmGestionUsuarios ventana = new FrmGestionUsuarios(this.rolAdmin);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionUserActionPerformed

    private void btnGestionManteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionManteActionPerformed
        FrmGestionMante ventanaGestion = new FrmGestionMante(this.rolAdmin);
        ventanaGestion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionManteActionPerformed

    private void btnGestionVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionVehiculosActionPerformed
        FrmGestionVehiculos ventana = new FrmGestionVehiculos(this.rolAdmin);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionVehiculosActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Loggin login = new Loggin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAsigancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsigancionActionPerformed
        FrmAsignarMantenimiento ventana = new FrmAsignarMantenimiento(this.rolAdmin);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAsigancionActionPerformed

    private void btnBoletaCombusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletaCombusActionPerformed
        FrmBoletaCombus ventana = new FrmBoletaCombus(this.rolAdmin);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBoletaCombusActionPerformed

    private void btnGestionMecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionMecaActionPerformed
        FrmGestionMecanicos ventana = new FrmGestionMecanicos(this.rolAdmin);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionMecaActionPerformed

    private void btnBoletatallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletatallerActionPerformed
        FrmBoletaTaller ventana = new FrmBoletaTaller(this.rolAdmin);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBoletatallerActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        FrmMenuVenci ventana = new FrmMenuVenci(this.rolAdmin);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
         FrmBoletaCambiarContra ventana = new FrmBoletaCambiarContra(this.rolAdmin,this.nameUser);
         ventana.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnChangePassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new FrmMenuAdmin(false,"").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsigancion;
    private javax.swing.JButton btnBoletaCombus;
    private javax.swing.JButton btnBoletataller;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnGestionMante;
    private javax.swing.JButton btnGestionMeca;
    private javax.swing.JButton btnGestionUser;
    private javax.swing.JButton btnGestionVehiculos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JPanel jPanelContenedorCentrado;
    private javax.swing.JPanel jPanelGridBotones;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelTarjetaMenu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}