/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.MenusPrincipales;
import Presentacion.AsignacionMante.FrmAsignarMantenimiento;
import Presentacion.BoletaCombus.FrmBoletaCombus;
import Presentacion.BoletaTaller.FrmBoletaTaller;
import Presentacion.Gmante.FrmGestionMante;
import Presentacion.Reportes.FrmMenuVenci;
/**
 *
 * @author triamus
 */
public class FrmMenuOperador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuOperador.class.getName());
    private boolean rolOperador;
    
    /**
     * Creates new form FrmMenuOperador
     */
    public FrmMenuOperador(boolean rol) {
        initComponents();
        this.rolOperador = rol;
        setLocationRelativeTo(null); // Centra la ventana en pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelContenedorCentrado = new javax.swing.JPanel();
        jPanelTarjetaMenu = new javax.swing.JPanel();
        lblSubtitulomenu = new javax.swing.JLabel();
        jPanelGridBotones = new javax.swing.JPanel();
        btnGestionMantenimientos = new javax.swing.JButton();
        btnAsigancion = new javax.swing.JButton();
        btnBoletaCombus = new javax.swing.JButton();
        btnBoletaTaller = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DELTAMOTORS - OPERADORES");
        setMinimumSize(new java.awt.Dimension(720, 520));

        jPanelPrincipal.setBackground(new java.awt.Color(240, 243, 246));
        jPanelPrincipal.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(41, 128, 185));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("DELTAMOTORS - OPERADOR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 10, 20);
        jPanelPrincipal.add(lblTitulo, gridBagConstraints);

        jSeparator1.setForeground(new java.awt.Color(200, 200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        jPanelPrincipal.add(jSeparator1, gridBagConstraints);

        jPanelContenedorCentrado.setOpaque(false);
        jPanelContenedorCentrado.setLayout(new java.awt.GridBagLayout());

        jPanelTarjetaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTarjetaMenu.setLayout(new java.awt.GridBagLayout());

        lblSubtitulomenu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSubtitulomenu.setForeground(new java.awt.Color(127, 140, 141));
        lblSubtitulomenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulomenu.setText("Panel de Control y Gestión del Sistema");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jPanelTarjetaMenu.add(lblSubtitulomenu, gridBagConstraints);

        jPanelGridBotones.setOpaque(false);
        jPanelGridBotones.setLayout(new java.awt.GridLayout(5, 2, 16, 14));

        btnGestionMantenimientos.setBackground(new java.awt.Color(41, 128, 185));
        btnGestionMantenimientos.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGestionMantenimientos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionMantenimientos.setText("Gestión Mantenimientos");
        btnGestionMantenimientos.setFocusPainted(false);
        btnGestionMantenimientos.setPreferredSize(new java.awt.Dimension(230, 42));
        btnGestionMantenimientos.addActionListener(this::btnGestionMantenimientosActionPerformed);
        jPanelGridBotones.add(btnGestionMantenimientos);

        btnAsigancion.setBackground(new java.awt.Color(41, 128, 185));
        btnAsigancion.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAsigancion.setForeground(new java.awt.Color(255, 255, 255));
        btnAsigancion.setText("Asignacion Mantenimientos");
        btnAsigancion.setFocusPainted(false);
        btnAsigancion.setPreferredSize(new java.awt.Dimension(230, 42));
        btnAsigancion.addActionListener(this::btnAsigancionActionPerformed);
        jPanelGridBotones.add(btnAsigancion);

        btnBoletaCombus.setBackground(new java.awt.Color(52, 73, 94));
        btnBoletaCombus.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnBoletaCombus.setForeground(new java.awt.Color(255, 255, 255));
        btnBoletaCombus.setText("Boleta de Combustible");
        btnBoletaCombus.setFocusPainted(false);
        btnBoletaCombus.setPreferredSize(new java.awt.Dimension(230, 42));
        btnBoletaCombus.addActionListener(this::btnBoletaCombusActionPerformed);
        jPanelGridBotones.add(btnBoletaCombus);

        btnBoletaTaller.setBackground(new java.awt.Color(52, 73, 94));
        btnBoletaTaller.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnBoletaTaller.setForeground(new java.awt.Color(255, 255, 255));
        btnBoletaTaller.setText("Boleta de Taller");
        btnBoletaTaller.setFocusPainted(false);
        btnBoletaTaller.setPreferredSize(new java.awt.Dimension(230, 42));
        btnBoletaTaller.addActionListener(this::btnBoletaTallerActionPerformed);
        jPanelGridBotones.add(btnBoletaTaller);

        btnReportes.setBackground(new java.awt.Color(52, 73, 94));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes Vencidos");
        btnReportes.setFocusPainted(false);
        btnReportes.setPreferredSize(new java.awt.Dimension(230, 42));
        btnReportes.addActionListener(this::btnReportesActionPerformed);
        jPanelGridBotones.add(btnReportes);

        jButton9.setBackground(new java.awt.Color(52, 73, 94));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Cambiar contrasena");
        jButton9.setFocusPainted(false);
        jButton9.setPreferredSize(new java.awt.Dimension(230, 42));
        jPanelGridBotones.add(jButton9);

        btnCerrarSesion.setBackground(new java.awt.Color(231, 76, 60));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(230, 42));
        jPanelGridBotones.add(btnCerrarSesion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanelTarjetaMenu.add(jPanelGridBotones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanelContenedorCentrado.add(jPanelTarjetaMenu, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 25, 20);
        jPanelPrincipal.add(jPanelContenedorCentrado, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionMantenimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionMantenimientosActionPerformed
        FrmGestionMante ventana = new FrmGestionMante(this.rolOperador);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionMantenimientosActionPerformed

    private void btnAsigancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsigancionActionPerformed
        FrmAsignarMantenimiento ventana = new FrmAsignarMantenimiento(this.rolOperador);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAsigancionActionPerformed

    private void btnBoletaCombusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletaCombusActionPerformed
        FrmBoletaCombus ventana = new FrmBoletaCombus(this.rolOperador);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBoletaCombusActionPerformed

    private void btnBoletaTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletaTallerActionPerformed
        FrmBoletaTaller ventana = new FrmBoletaTaller(this.rolOperador);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBoletaTallerActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        FrmMenuVenci ventana = new FrmMenuVenci(this.rolOperador);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new FrmMenuOperador(false).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsigancion;
    private javax.swing.JButton btnBoletaCombus;
    private javax.swing.JButton btnBoletaTaller;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionMantenimientos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanelContenedorCentrado;
    private javax.swing.JPanel jPanelGridBotones;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelTarjetaMenu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSubtitulomenu;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}